kind: ServiceAccount
apiVersion: v1
metadata:
  name: edp-kaniko
  namespace: {{ .Values.global.edpName }}
  {{- if .Values.kaniko.roleArn  }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.kaniko.roleArn }}
  {{ end }}
