{{- if .Values.global.database.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.global.database.name}}
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.global.database.storage.size}}
  storageClassName: {{.Values.global.database.storage.class}}
  volumeMode: Filesystem
{{end}}