{{- if eq .Values.global.platform "openshift" -}}
apiVersion: v1.edp.epam.com/v1alpha1
kind: EDPComponent
metadata:
  name: docker-registry
spec:
  type: docker-registry
  url: {{ .Values.dockerRegistry.url }}
  visible: false
  icon: stub-value
{{end}}