{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: v1.edp.epam.com/v1alpha1
kind: EDPComponent
metadata:
  name: kubernetes
spec:
  type: kubernetes
  url: {{ required "A valid .Values.global.webConsole.url entry is required!" .Values.global.webConsole.url }}
  visible: false
  icon: stub-value
{{end}}
