{{- if not (lookup "v1" "ConfigMap" ".Values.global.edpName" "edp-config").metadata }}
apiVersion: v1
data:
  aws_region: {{ required "A valid .Values.awsRegion entry is required!" .Values.awsRegion }}
  edp_name: {{ .Values.global.edpName }}
  edp_version: {{.Values.global.version}}
  dns_wildcard: {{ .Values.global.dnsWildCard }}
  perf_integration_enabled: "{{ .Values.perf.enabled }}"
  vcs_integration_enabled: "{{ .Values.vcs.enabled }}"
kind: ConfigMap
metadata:
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
  name: edp-config
{{end}}