apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: gitlab-ci
    {{- include "edp-install.labels" . | nindent 4 }}
  name: gitlab-ci
  namespace: {{ .Values.global.edpName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-ci
subjects:
- kind: ServiceAccount
  name: gitlab-ci
  namespace: {{ .Values.global.edpName }}