apiVersion: v1
data:
  ist.json: |
            {
              "apiVersion": "v2.edp.epam.com/v1alpha1",
              "kind": "ImageStreamTag",
              "metadata": {
                "name": "replace"
              },
              "spec": {
                "codebaseImageStreamName": "replace",
                "tag": "replace"
              }
            }
kind: ConfigMap
metadata:
  name: ist-template
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}